const COUNTRY_LABELS = {
  grc: 'Greece',
  usa: 'United States',
  gbr: 'United Kingdom',
  deu: 'Germany',
  cyp: 'Cyprus',
  aus: 'Australia',
  fra: 'France',
  can: 'Canada',
  che: 'Switzerland',
  nld: 'Netherlands',
  swe: 'Sweden',
  ita: 'Italy',
  bel: 'Belgium',
  esp: 'Spain',
  aut: 'Austria',
  dnk: 'Denmark',
  nor: 'Norway',
  irl: 'Ireland',
  zaf: 'South Africa',
  fin: 'Finland',
  are: 'United Arab Emirates',
  bra: 'Brazil',
  chn: 'China',
  cze: 'Czech Republic',
  sau: 'Saudi Arabia',
  sgp: 'Singapore',
  isr: 'Israel',
  lux: 'Luxembourg',
  rus: 'Russia',
  jpn: 'Japan',
  prt: 'Portugal',
  qat: 'Qatar',
  tur: 'Turkey',
  pol: 'Poland',
  nzl: 'New Zealand',
  hun: 'Hungary',
  kwt: 'Kuwait',
  hkg: 'Hong Kong',
  kor: 'South Korea',
  chl: 'Chile',
  kaz: 'Kazakhstan',
  ind: 'India',
  mex: 'Mexico',
  rou: 'Romania',
  twn: 'Taiwan',
  bgr: 'Bulgaria',
  arg: 'Argentina',
  srb: 'Serbia',
  lbn: 'Lebanon',
  mlt: 'Malta',
  tha: 'Thailand',
  ukr: 'Ukraine',
  est: 'Estonia',
  egy: 'Egypt',
  alb: 'Albania',
  ecu: 'Ecuador',
  svn: 'Slovenia',
  ltu: 'Lithuania',
  hrv: 'Croatia',
  idn: 'Indonesia',
  bhr: 'Bahrain',
  omn: 'Oman',
  isl: 'Iceland',
  mkd: 'North Macedonia',
  svk: 'Slovakia',
  pan: 'Panama',
  vnm: 'Vietnam',
  vir: 'U.S. Virgin Islands',
  mar: 'Morocco',
  irq: 'Iraq',
  kgz: 'Kyrgyzstan',
  cri: 'Costa Rica',
  eth: 'Ethiopia',
  cub: 'Cuba',
  wsm: 'Samoa',
  tto: 'Trinidad and Tobago',
  geo: 'Georgia',
  grd: 'Grenada',
  bwa: 'Botswana',
  brn: 'Brunei',
  cmr: 'Cameroon',
  civ: "Côte d'Ivoire",
  col: 'Colombia',
  dza: 'Algeria',
  aze: 'Azerbaijan',
  arm: 'Armenia',
  brb: 'Barbados',
  irn: 'Iran',
  kna: 'Saint Kitts and Nevis',
  khm: 'Cambodia',
  lie: 'Liechtenstein',
  lso: 'Lesotho',
  mys: 'Malaysia',
  moz: 'Mozambique',
  nga: 'Nigeria',
  mco: 'Monaco',
  mac: 'Macau',
  lva: 'Latvia',
  per: 'Peru',
  rom: 'Romania',
  sle: 'Sierra Leone',
  sen: 'Senegal',
  png: 'Papua New Guinea',
  syc: 'Seychelles',
  uga: 'Uganda',
  ury: 'Uruguay',
  ven: 'Venezuela',
  yug: 'Yugoslavia'
};
